import turtle

turtle.colormode(255)
t = turtle.Turtle()
t.speed(2)
t.pencolor("Gray")
t.penup()
t.sety(-80)
t.setx(-60)
t.pendown()
#length = int(input("Enter map length: "))
length = 300
mid_length = length//3
#breadth = int(input("Enter map breadth: "))
breadth = 150

t.fillcolor(27,115,57)
t.begin_fill()
t.left(180)
t.forward(mid_length)
t.right(90)
t.forward(breadth)
t.right(90)
t.forward(mid_length)
t.right(90)
t.forward(breadth)
t.end_fill()

t.fillcolor(27,115,57)
t.begin_fill()
t.left(90)
t.forward(2*mid_length)
t.left(90)
t.forward(breadth)
t.left(90)
t.forward(mid_length)
t.left(90)
t.forward(breadth)
t.end_fill()

t.fillcolor(255, 255, 255)
t.begin_fill()
t.penup()
t.right(180)
t.forward(breadth)
t.left(90)
t.pendown()
t.forward(mid_length)
t.left(90)
t.forward(breadth)
t.end_fill()
